repos:
  # Code formatting
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=88]
        files: ^src/.*\.py$

  # Import sorting
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [--profile=black, --line-length=88]
        files: ^src/.*\.py$

  # Linting
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-pyproject
        files: ^src/.*\.py$

  # Basic type checking - only major errors
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies:
          - types-requests
          - click
        args:
          - --ignore-missing-imports
          - --disable-error-code=unused-ignore
          - --disable-error-code=no-any-return
          - --disable-error-code=unreachable
        files: ^src/.*\.py$

  # General code quality
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: ^(spikes/|htmlcov/)
      - id: end-of-file-fixer
        exclude: ^(spikes/|htmlcov/)
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: debug-statements
        files: ^src/.*\.py$
